title: LAB3142
description: Digital Writing Laboratory
baseurl: ""
url: "https://lab3142.com"

markdown: kramdown
highlighter: rouge
permalink: /writings/:title/

collections:
  posts:
    output: true
    permalink: /writings/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"